package com.custard.ehr.shared.security;

public enum Permission {
    PATIENT_REGISTER,
    PATIENT_VIEW,

    ENCOUNTER_CREATE,
    ENCOUNTER_VIEW,
    ENCOUNTER_COMPLETE,
    ENCOUNTER_CANCEL,

    VITALS_RECORD,
    VITALS_VIEW,

    CONSULTATION_WRITE,
    CONSULTATION_VIEW,

    PRESCRIPTION_CREATE,
    PRESCRIPTION_VIEW,
    PRESCRIPTION_CANCEL,

    DRUG_VIEW,
    DRUG_MANAGE,

    LAB_TEST_MANAGE,
    LAB_ORDER_CREATE,
    LAB_ORDER_VIEW,
    LAB_RESULT_WRITE,

    PHARMACY_DISPENSE,
    PHARMACY_VIEW,
    STOCK_MANAGE,
    STOCK_VIEW,

    INVOICE_CREATE,
    INVOICE_VIEW,
    PAYMENT_RECORD,
    PAYMENT_VIEW,
    PAYMENT_WAIVE,

    USER_VIEW,
    USER_MANAGE,

    AUDIT_VIEW
}