spring.application.name=ehr
security.jwt.secret=a-very-long-and-secure-secret-key-that-is-at-least-32-chars
security.jwt.expiration-minutes=10
security.jwt.access-token-expiration-minutes=60
security.jwt.refresh-token-expiration-minutes=10080

# Basic Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ehr
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Spring Modulith Event Publication Registry
# This ensures that even if you use Async events, they are persisted to the DB
# so no data is lost if the app crashes.
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true

# Optional: If you want to use a specific schema for your modules
# spring.jpa.properties.hibernate.default_schema=public

